### ISSUE TITLE
Create GitHub release

### ISSUE THREAD

**Issue by hwittenborn** [8go/matrix-commander-rs#1]
Hi! I just saw this project after [creating a similar project](/hwittenborn/shoot) that was basically gonna be matrix-commander in Rust, but then I saw this and I didn't see much point in it anymore.

Anyway, I definitely would prefer to just use this, but I'd like to package it up first, and doing so would require a release to download from. Would it be possible to create a release so I could do such?

**Comment by 8go** [comment]
Hi @hwittenborn 

You can always contribute to `matrix-commander-rs`. There is plenty to do! Feel free to add your desired features by creating PRs. 

`matrix-commander-rs` is listed on https://crates.io/crates/matrix-commander and here (Github).

Standard Rust procedure: 
- download from Github, 
- cd into directory
- run `cargo build` or `cargo build --release`
- and you have an executable for your platform. 

A task item on the To-Do list is: create a GitHub action so that on each git push it creates a release automatically, e.g. for a popular platform like Ubuntu. If you have experience with Github actions or want to learn something new, try to create such an `action`. You can do that for a Rust project in your Github account and once it works we adapt it and make a PR here. 

Just some ideas :smile:

**Comment by hwittenborn** [comment]
Hey! I'd be down with implementing an automated action, but at least for the time being could a manual release be made here? I've been trying to package this up and it'd just be nicer if there could be a release now and then needed automation could be set up for future releases.

**Comment by 8go** [comment]
As exception I can do one and only one manual release here. But this is definitely not the way forward, automation is key to everything. Also helps with reproducibility, consistency, ...

**Comment by 8go** [comment]
What are your planning to do with the release? 

Is it for publication on https://mpr.makedeb.org?

**Comment by 8go** [comment]
Github action workflow has been written. In the future releases will show up automatically.

**Comment by hwittenborn** [comment]
Thanks for getting that written up! I'll have the MPR package up sometime soon too

**Comment by 8go** [comment]
Let me know when the MPR package is in place :)  :+1:

**Comment by hwittenborn** [comment]
Yo sorry for the delay in the MPR package, I've been busy with another project at the moment and I haven't gotten around to getting this packaged yet. I do want to still, I just wanted to give a heads up that I've just been doing some other stuff right now.

**Comment by 8go** [comment]
@hwittenborn   No hurry, take your time!

**Comment by hwittenborn** [comment]
I'm getting this packaged up right now @8go - are you fine if I name the Rust version of the package `matrix-commander`, or do you want it to be `matrix-commander-rs`? I want the first, but I don't know how feature complete this Rust version currently is and if you'd just want otherwise or anything.

**Comment by 8go** [comment]
Are you only packaging Rust applications? If so, `matrix-commander` is fine. Then there is no confusion, if all is Rust.

If you are packaging all sorts of apps, Python, Rust, Java, etc. then I think it is better to use name `matrix-commander-rs` (so that you can later package the Python version and so that people understand the difference). 

The Py and Rust version are NOT equal, Py has more features.

**Comment by hwittenborn** [comment]
Got it - yeah I package a bunch of different stuff in different languages, so I'll do `matrix-commander-rs` then. I'll send a message when it's all done.

**Comment by 8go** [comment]
Yes, I think in this case as you said, `matrix-commander-rs` is better.

**Comment by hwittenborn** [comment]
Sorry again for the delay @8go, I've been busy with that side project again and it started taking up a bunch of my time again :P. I finally got it packaged up on the [MPR](https://mpr.makedeb.org/packages/matrix-commander-rs) though - would you be open to a PR to add instructions for installing it?
